# https://taskfile.dev

version: '3'

tasks:
  run:
    cmds:
      - dotnet run -c Release --project src/AOC/AOC.fsproj -- {{.CLI_ARGS}}

  benchmark:
    cmds:
      - dotnet run -c Release --project src/AOC/AOC.fsproj -- benchmark {{.CLI_ARGS}}

